# Generated by Django 5.0.1 on 2024-04-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_repository_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.folder')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.repository')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.repository')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.folder')),
            ],
        ),
    ]
