# Generated by Django 5.0.1 on 2024-04-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_folder_parent_remove_folder_repository_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipFile', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.repository')),
            ],
        ),
    ]
