# Generated by Django 5.0.1 on 2024-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performed_by', models.CharField(max_length=35)),
                ('event', models.CharField(max_length=35)),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
