# Generated by Django 5.0.1 on 2024-04-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Performed_by',
        ),
    ]
