# Generated by Django 5.0.1 on 2024-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
